config/routes.rb
Yava::Application.routes.draw do

	root 'home#index'
	
	match "/search", to: "home#search", via: "get"
	match "/search", to: "home#search", via: "post"
	match "/msearch", to: "home#msearch", via: "get"
	match "/msearch", to: "home#msearch", via: "post"
	match "/about", to: "home#about", via: "get"
	match "/index", to: "home#index", via: "get"
	match "/sitemap", to: "home#sitemap", via: "get"
	match "/tos", to: "home#tos", via: "get"
	match "/pp", to: "home#pp", via: "get"
	match "/stat", to: "home#stat", via: "get"

	match "/signin", to: "users#signin", via: "get"
	match "/auth/:provider/callback", :to => "sessions#create", via: "get"
	match "/auth/failure", :to => "sessions#failure", via: "get"
	match "/signout", :to => "sessions#destroy", via: "get"
	match "/users/:id/email", to: "users#email", via: "get"

	resources :ingredients
	resources :ingredient_synonyms
	resources :products
	resources :users
	resources :manufacturers
	resources :brands
	resources :cities
	resources :labels
	resources :features
	resources :nutvals

	resources :inquiries
	match "/inquiries/new", to: "inquiries#create2", via: "post"
	resources :comments

	resources :j_product_features
	resources :j_product_labels
	resources :j_ingredient_classnames
	
	resources :classnames
	resources :packagematerials
	resources :categories
	resources :subcategories
	resources :veganities

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id                 :integer          not null, primary key
#  name               :string(255)      not null
#  description        :text
#  veganity_id        :integer          default(4), not null
#  image              :string(255)
#  source             :string(255)
#  user_id            :integer          not null
#  hide               :boolean          default(FALSE), not null
#  fixed              :boolean          default(FALSE), not null
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Ingredient < ActiveRecord::Base
  before_save { self.name = UnicodeUtils.downcase(self.name) }
	validates :name, presence: true, uniqueness: {case_sensitive: false}
	validates :veganity_id, presence: true
	validates :user_id, presence: true
	validates :hide, :inclusion => { :in => [true, false] }

	has_many :j_product_ingredient
	has_many :products, :through => :j_product_ingredient #, foreign_key: :product_id, class_name: "Product"

#	has_many :products, class_name: "Product"
	has_many :j_ingredient_product
	has_many :product, :through => :j_ingredient_product
	
#	has_many :classname
	
	has_many :ingredient_synonym
	
	belongs_to :veganity
	belongs_to :user
	
	has_many :j_ingredient_classname
	has_many :classname, :through => :j_ingredient_classname

	# paperclip image stuff
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	# http://stackoverflow.com/questions/3181845/validate-attachment-content-type-paperclip
	#validates_attachment_content_type :image, :content_type => /^image\/(png|gif|jpg|jpeg)/
	#validates_attachment :image, :size => { :in => 0..500.kilobytes }

	# return all names (with synonyms)
	def get_names
	  if !ingredient_synonym.blank?
	    UnicodeUtils.titlecase(name) + ", " + ingredient_synonym.map do |i|
	      UnicodeUtils.titlecase(i.name)
	    end.join(", ")
	  else
	    UnicodeUtils.titlecase(name)
	  end
	end
	
	# return all synonyms
	def get_synonyms
	  if !ingredient_synonym.blank?
	    ingredient_synonym.map do |i|
	      UnicodeUtils.titlecase(i.name)
	    end.join(", ")
	  end
	end
	
	# return all classnames
	def get_classnames
	  if classname.any?
	    classname.map do |c|
	      c.get_sg
	    end.join(", ")
	  end
	end
	
	# compute the veganity of an array which contains the veganities of the products which contain only this ingredient
	def compute_veganity(arr)
		# vegan + not vegan = uncertain
		if arr.include?(Veganity::VEGAN) and arr.include?(Veganity::NOT_VEGAN)
		  Veganity::UNCERTAIN
		elsif arr.include?(Veganity::UNCERTAIN)
		  Veganity::UNCERTAIN
		# not vegan
		elsif arr.include?(Veganity::NOT_VEGAN)
		  Veganity::NOT_VEGAN
		# vegan
		elsif arr.include?(Veganity::VEGAN)
		  Veganity::VEGAN
		# unknown
		else
		  Veganity::UNKNOWN
		end
	end

	# calculate the veganity of this ingredient by using an array and compute_veganity
	def update_veganity
	  arr = []
	  # products which contain only this ingredient = product
	  self.product.map do |p|
	    # TODO: contains the old veganities (not updated, at most one hour old)
	    arr << p.veganity_id
	  end
	  #veganity_id
	  #j_ingredient_product.map do |p|
	  #	p.update(veganity)
	  #if !self.fixed
	    #self.update(veganity_id: compute_veganity(arr))
	  #end
	  if self.fixed
	    self.veganity_id
	  else
	    if arr.any?
	      logger.debug arr
	      compute_veganity(arr)
	    else
	      Veganity::UNKNOWN
	    end
	  end
	end
end

app/controllers/ingredients_controller.rb
# IngredientsController
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.where("not hide").paginate(:page => params[:page])
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    #@ingredient.update_veganity
    @ingredient.update(veganity_id: @ingredient.update_veganity)
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
    if !current_user
      redirect_to @ingredient, alert: t("no_rights_signin_complete")
    end
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.user_id = current_user.id
    # http://wowkhmer.com/2011/09/09/use-view-helper-methods-in-rails-3-controller/
    @ingredient.name = view_context.rm_umlaute(@ingredient.name)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: t("controller.created", model: t("activerecord.models.ingredient")) }
        format.json { render action: 'show', status: :created, location: @ingredient }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    @veganity_old = @ingredient.veganity_id
    @veganity_new = ingredient_params[:veganity_id]
    # TODO: @ingredient.name = view_context.rm_umlaute(@ingredient.name)
    respond_to do |format|
      if @ingredient.update(ingredient_params)
         format.html { redirect_to @ingredient, notice: t("controller.updated", model: t("activerecord.models.ingredient")) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find_by_id(params[:id].to_i)
      if @ingredient.blank?
	redirect_to ingredients_path, alert: t("controller.notfound", model: t("activerecord.models.ingredient"))
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description, :veganity_id, :image, :source, :user_id, :classname_id, :hide, :fixed)
    end

end

app/helpers/ingredients_helper.rb
# IngredientsHelper
module IngredientsHelper

  # http://stackoverflow.com/questions/12005739/replace-umlauts-in-ruby-on-rails
  # 
  # this removes the umlaute from an ingredient and returns the "clean" ingredient
  def rm_umlaute(ingredient)
    ingredient.gsub!(/[äöüßÄÖÜ]/) do |match|
      case match
	when "ä" then "ae"
	when "ö" then "oe"
	when "ü" then "ue"
	when "ß" then "ss"
	when "Ä" then "Ae"
	when "Ö" then "Oe"
	when "Ü" then "Ue"
      end
    end
    ingredient
  end

end

app/views/ingredients/_form.html.erb
<%# provide(:title, t("form.edit", model: t(:ingredients_title, count: 1))+": "+UnicodeUtils.titlecase(@ingredient.name)) %>

<% if current_user %>
  <% if current_user.permission_id >= User::PERMISSIONS_INGREDIENT %>
	<%= simple_form_for @ingredient, :html => { :class => 'form-horizontal' } do |f| %>
		<%= render "layouts/submit_error", :errors => @ingredient.errors %>
		<%= f.input :name %>
		<% if !@ingredient.id.blank? %>
		  <%= f.input :ingredient_synonym do %>
		    <a role="button" href="#ingredient_synonym" class="btn" data-toggle="modal"><%= !@ingredient.ingredient_synonym.any? ? t(:form_add) : t(:form_edit) %></a>
		  <% end %>
		<% end %>
		<%#= f.input :ingredient_synonym %>
		<%#= f.input :classname_id, collection: Classname.order("lower(sg) asc"), label_method: :get_sg_w_abbr %>
		<% if !@ingredient.id.blank? %>
		  <%= f.input :classname do %>
		    <a role="button" href="#ingredient_classname" class="btn" data-toggle="modal"><%= !@ingredient.classname.any? ? t(:form_add) : t(:form_edit) %></a>
		  <% end %>
		<% end %>
		<%= f.input :image %>
		<%= f.input :description, :input_html => { :class => "span8", :rows => 10 } %>
		<%= f.input :source %>
		<%= f.input :hide, as: :boolean %>
		<% if current_user.permission_id >= User::PERMISSIONS_ADMIN %>
		    <%= f.input :veganity_id, :collection => Veganity.all, include_blank: false %>
		    <%= f.input :fixed, as: :boolean %>
		<% end %>
		<div class="form-actions">
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.button :submit, :class => 'btn-primary' %>
			<%= submit_tag t(:form_cancel), :type => :reset, :class => "btn btn-danger" %>
		</div>
	<% end %>
	<% if !@ingredient.id.blank? %>
	  <%= render "ingredients/ingredient_synonym_form" %>
	  <%= render "ingredients/ingredient_classname_form" %>
	<% end %>
  <% else %>
    <%= t(:no_rights2) %>
  <% end %>
<% else %>
	<%= no_rights %>
<% end %>

app/views/ingredients/_ingredient_classname_form.html.erb
<% if current_user %>

<div id="ingredient_classname" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-focus-on="input:first">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= t("j_ingredient_classnames_title.other") %></h3>
  </div>

  <div class="modal-body">
    <div class="ingredient_classnames">
      <% @ingredient.classname.map do |c| %>
	<p>
	  <%#= link_to c.get_sg, ???ingredient_path() %>
	  <%= c.get_sg %>
	  <%= link_to "<i class='icon-minus'></i>".html_safe, j_ingredient_classname_path(c.id), :onclick => "$(this).parents('p').remove();", :remote => true, :method => :delete %>
	</p>
      <% end %>
    </div>
  
  <% @ingredient_classname = JIngredientClassname.new %>
	<%= simple_form_for @ingredient_classname, :html => { :class => 'form-horizontal' }, :remote => true do |f| %>
	<div class="j_ingredient_classname-errors"></div>
		  <%= f.hidden_field :ingredient_id, value: @ingredient.id %>
		  <%= f.input :classname_id, collection: Classname.order("LOWER(sg) ASC"), label_method: :get_sg_w_abbr, hint: "<a role='button' class='btn' onclick=\"$(this).parents('form').submit();\">#{t(:form_add)}</a>" %>

	<div class="form-actions">
		<%#= f.button :submit, :class => 'btn-primary' %>
		<%= submit_tag t(:form_cancel), :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
	</div>
<% end %>

</div>
</div>

<% else %>
	<%= no_rights %>
<% end %>

app/views/ingredients/_ingredient_synonym_form.html.erb
<% if current_user %>

<div id="ingredient_synonym" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-focus-on="input:first">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= t("ingredient_synonyms_title.other") %></h3>
  </div>

  <div class="modal-body">
		  <div class="ingredient_synonyms">
	<%# @product.ingredient_synonym.select(["labels.name", "ingredient_synonyms.id"]).joins(:label).order("labels.name ASC").map do |l| %>
	<% @ingredient.ingredient_synonym.map do |i| %>
	<p>
		<%= i.name %>
		<%= link_to "<i class='icon-minus'></i>".html_safe, ingredient_path(i.id), :onclick => "$(this).parents('p').remove();", :remote => true, :method => :delete %>
	</p>
	<% end %>
</div>

	<% @ingredient_synonym = IngredientSynonym.new %>
	<%= simple_form_for @ingredient_synonym, :html => { :class => 'form-horizontal' }, :remote => true do |f| %>
	<div class="ingredient_synonym-errors"></div>
		  <%= f.hidden_field :ingredient_id, value: @ingredient.id %>
		  <%#= f.input :label_id, collection: Label.order("LOWER(name) ASC"), hint: "<a role='button' class='btn' onclick=\"$(this).parents('form').submit();\">#{t(:form_add)}</a>" %>
		  <%= f.input :name, hint: "<a role='button' class='btn' onclick=\"$(this).parents('form').submit();\">#{t(:form_add)}</a>" %>

	<div class="form-actions">
		<%#= f.button :submit, :class => 'btn-primary' %>
		<%= submit_tag t(:form_cancel), :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
	</div>
<% end %>

</div>
</div>

<% else %>
	<%= no_rights %>
<% end %>

app/views/ingredients/edit.html.erb
<h1><%= t("form.edit", model: t("ingredients_title.one")) %></h1>

<%= render 'form' %>

<hr>
<p><%= link_to t(:link_show, model: t("ingredients_title.one")), @ingredient %> |
<%= link_to t(:link_show, model: t("ingredients_title.other")), ingredients_path %></p>

app/views/ingredients/index.html.erb
<% provide(:title, t("ingredients_title.other")) %>

<h1><%= t("ingredients_title.other") %></h1>

<p><%= link_to t("form.new", genus: t("form.f"), model: t("ingredients_title.one")), new_ingredient_path, { class: "btn" } %></p>
<hr>

<div class="center">
	<%= will_paginate @ingredients %>
</div>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
	  <th><%= t("activerecord.attributes.ingredient.name") %></th>
	  <th><%= t("activerecord.attributes.ingredient.description") %></th>
	  <th><%= t("activerecord.attributes.ingredient.veganity_id") %></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.where("not hide").order("lower(name) asc").each do |ingredient| %>
      <tr class="<%= ingredient.veganity.color %>">
        <td><%= link_to truncate(ingredient.get_names), ingredient %></td>
        <td><%= truncate(ingredient.description) %></td>
        <td>
	  <%= ingredient.veganity.name %>
	  <%= t(:veganity_fixed) if ingredient.fixed %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="center">
	<%= will_paginate @ingredients %>
</div>

<hr>
<p><%= link_to t("form.new", genus: t("form.f"), model: t("ingredients_title.one")), new_ingredient_path, { class: "btn" } %></p>

app/views/ingredients/new.html.erb
<h1><%= t("form.new", genus: t("form.f"), model: t("ingredients_title.one")) %></h1>

<%= render 'form' %>

<hr>
<p><%= link_to t(:link_back, model: t("ingredients_title.other")), ingredients_path %></p>

app/views/ingredients/show.html.erb
<% provide(:title, t(:ingredients_title, count: 1)+": "+UnicodeUtils.titlecase(@ingredient.name)) %>

<h2><%= UnicodeUtils.titlecase(@ingredient.name) %></h2>
<h3 class="center"><%= "hidden" if @ingredient.hide %></h3>

<% if @ingredient.ingredient_synonym.any? %>
  <p><b><%= t("activerecord.attributes.ingredient.ingredient_synonym") %>:</b>
  <%= @ingredient.get_synonyms %>
  </p>
<% end %>

<% if @ingredient.classname.any? %>
  <p><strong><%= t("activerecord.attributes.ingredient.classname") %>:</strong>
  <%= @ingredient.get_classnames %>
  </p>
<% end %>

<p><%= image_tag @ingredient.image.url(:medium), class: "img-polaroid" %></p>

<% if !@ingredient.description.blank? %>
<p><%= content_tag("pre", @ingredient.description) %></p>
<p><b><%= t("activerecord.attributes.ingredient.source") %></b>: <%= show_url @ingredient.source, @ingredient.source %></p>
<% end %>

<p><strong><%= t("activerecord.attributes.ingredient.veganity_id") %>:</strong></p>
  <table class="table table-condensed table-striped">
    <tr class="<%= @ingredient.veganity.color %>">
      <td>
	<%= @ingredient.veganity.name %>
	<%= t(:veganity_fixed) if @ingredient.fixed %>
      </td>
    </tr>
  </table>

<hr>

<% if !@ingredient.product.blank? %>
<p><b><%= t("activerecord.attributes.ingredient.product") %>:</b></p>
<table class="table table-condensed table-striped">
<tr>
  <th><%= t("activerecord.attributes.ingredient.product_id") %></th>
  <th><%= t("activerecord.attributes.ingredient.veganity_id") %></th>
</tr>
<% @ingredient.product.map do |i| %>
<tr class="<%= i.veganity.color %>">
  <td><%= link_to i.name, product_path(i.id) %></td>
  <td><%= i.veganity.name.capitalize %></td>
</tr>
<% end %>
</table>
<hr>
<% end %>

<% if !@ingredient.user_id.blank? %>
	<%= t(:submitted_by) %>
	<%= link_to @ingredient.user.nickname, user_path(@ingredient.user_id) %>
	<%= t(:submitted_when) +" "+ time_ago_in_words(@ingredient.created_at) %>
<% end %>
<hr>
<p>
<%= link_to t(:link_edit, model: t("ingredients_title.one")), edit_ingredient_path(@ingredient) %> |
<%= link_to t(:link_back, model: t("ingredients_title.other")), ingredients_path %>
</p>