config/routes.rb
Yava::Application.routes.draw do

	root 'home#index'
	
	match "/search", to: "home#search", via: "get"
	match "/search", to: "home#search", via: "post"
	match "/msearch", to: "home#msearch", via: "get"
	match "/msearch", to: "home#msearch", via: "post"
	match "/about", to: "home#about", via: "get"
	match "/index", to: "home#index", via: "get"
	match "/sitemap", to: "home#sitemap", via: "get"
	match "/tos", to: "home#tos", via: "get"
	match "/pp", to: "home#pp", via: "get"
	match "/stat", to: "home#stat", via: "get"

	match "/signin", to: "users#signin", via: "get"
	match "/auth/:provider/callback", :to => "sessions#create", via: "get"
	match "/auth/failure", :to => "sessions#failure", via: "get"
	match "/signout", :to => "sessions#destroy", via: "get"
	match "/users/:id/email", to: "users#email", via: "get"

	resources :ingredients
	resources :ingredient_synonyms
	resources :products
	resources :users
	resources :manufacturers
	resources :brands
	resources :cities
	resources :labels
	resources :features
	resources :nutvals

	resources :inquiries
	match "/inquiries/new", to: "inquiries#create2", via: "post"
	resources :comments

	resources :j_product_features
	resources :j_product_labels
	resources :j_ingredient_classnames
	
	resources :classnames
	resources :packagematerials
	resources :categories
	resources :subcategories
	resources :veganities

end

app/models/veganity.rb
# == Schema Information
#
# Table name: veganities
#
#  id                 :integer          not null, primary key
#  name               :string(255)      not null
#  description        :text
#  image              :string(255)
#  color              :string(255)      not null
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Veganity < ActiveRecord::Base
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  
  has_many :product
  has_many :ingredient
  has_many :inquiry
  has_many :comment
  
  # paperclip image stuff
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :image, :content_type => /^image\/(png|gif|jpg|jpeg)/
  #validates_attachment :image, :size => { :in => 0..500.kilobytes }
  
  # ID of VEGAN in the database (table veganities)
      VEGAN = 1
  # ID of NOT_VEGAN in the database (table veganities)
  NOT_VEGAN = 2
  # ID of UNCERTAIN in the database (table veganities)
  UNCERTAIN = 3
  # ID of UNKNOWN in the database (table veganities)
    UNKNOWN = 4
end

app/controllers/veganities_controller.rb
# VeganitiesController
class VeganitiesController < ApplicationController
  before_action :set_veganity, only: [:show, :edit, :update, :destroy]

  # GET /veganities
  # GET /veganities.json
  def index
    @veganities = Veganity.paginate(:page => params[:page])
  end

  # GET /veganities/1
  # GET /veganities/1.json
  def show
  end

  # GET /veganities/new
  def new
    @veganity = Veganity.new
  end

  # GET /veganities/1/edit
  def edit
  end

  # POST /veganities
  # POST /veganities.json
  def create
    @veganity = Veganity.new(veganity_params)

    respond_to do |format|
      if @veganity.save
        format.html { redirect_to @veganity, notice: 'Veganity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @veganity }
      else
        format.html { render action: 'new' }
        format.json { render json: @veganity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veganities/1
  # PATCH/PUT /veganities/1.json
  def update
    respond_to do |format|
      if @veganity.update(veganity_params)
        format.html { redirect_to @veganity, notice: 'Veganity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @veganity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veganities/1
  # DELETE /veganities/1.json
  def destroy
    @veganity.destroy
    respond_to do |format|
      format.html { redirect_to veganities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veganity
      @veganity = Veganity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veganity_params
      params.require(:veganity).permit(:name, :description, :image, :color)
    end
end

app/helpers/veganities_helper.rb
# VeganitiesHelper
module VeganitiesHelper
end

app/views/veganities/_form.html.erb
<% if current_user %>
<%= simple_form_for(@veganity, :html => { :class => 'form-horizontal' }) do |f| %>
	<%= render "layouts/submit_error", :errors => @veganity.errors %>

	<div class="form-inputs">
		<%= f.input :name %>
		<%= f.input :description %>
		<%= f.input :image %>
		<%= f.input :color %>
	</div>

	<div class="form-actions">
		<%= f.button :submit, :class => 'btn-primary' %>
		<%= submit_tag t(:form_cancel), :type => :reset, :class => "btn btn-danger" %>
	</div>
<% end %>
<% else %>
	<%= no_rights %>
<% end %>

app/views/veganities/edit.html.erb
<h1><%= t("form.edit", model: t("veganities_title.one")) %></h1>

<%= render 'form' %>

<hr>

<p>
	<%= link_to t(:link_show, model: t("veganities_title.one")), @veganity %> |
	<%= link_to t(:link_back, model: t("veganities_title.other")), veganities_path %>
</p>

app/views/veganities/index.html.erb
<% provide(:title, t(:veganities_title, count: 2)) %>

<h1><%= t("veganities_title.other") %></h1>

<div class="center">
	<%= will_paginate @veganities %>
</div>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
						<th><%= t("activerecord.attributes.veganity.image") %></th>
						<th><%= t("activerecord.attributes.veganity.name") %></th>
						<th><%= t("activerecord.attributes.veganity.description") %></th>
					</tr>
	</thead>

	<tbody>
		<% @veganities.order("name ASC").each do |veganity| %>
		<tr>
		  <td><%= image_tag veganity.image.url(:thumb), class: "img-polaroid" %></td>
		  <td><%= link_to veganity.name, veganity_path(veganity) %></td>
		  <td><%= veganity.description %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<div class="center">
	<%= will_paginate @veganities %>
</div>

<hr>

<p>
	<%= link_to t("form.new", genus: t("form.f"), model: t("veganities_title.one")), new_veganity_path %>
</p>

app/views/veganities/new.html.erb
<h1><%= t("form.new", genus: t("form.f"), model: t("veganities_title.one")) %></h1>

<%= render 'form' %>

<hr>

<p>
	<%= link_to t(:link_back, model: t("veganities_title.other")), veganities_path %>
</p>

app/views/veganities/show.html.erb
<% provide(:title, t(:veganities_title, count: 1)+": "+@veganity.name) %>

<h1><%= @veganity.name %></h1>

<p>
	<b><%= t("activerecord.attributes.veganity.description") %>:</b>
	<%= @veganity.description %>
</p>

<p>
	<b><%= t("activerecord.attributes.veganity.image") %>:</b>
	<%= image_tag @veganity.image.url(:medium), class: "img-polaroid" %>
</p>

<hr>

<p>
	<%= link_to t(:link_edit, model: t("veganities_title.one")), edit_veganity_path(@veganity) %> |
	<%= link_to t(:link_back, model: t("veganities_title.other")), veganities_path %>
</p>