config/routes.rb
Yava::Application.routes.draw do

	root 'home#index'
	
	match "/search", to: "home#search", via: "get"
	match "/search", to: "home#search", via: "post"
	match "/msearch", to: "home#msearch", via: "get"
	match "/msearch", to: "home#msearch", via: "post"
	match "/about", to: "home#about", via: "get"
	match "/index", to: "home#index", via: "get"
	match "/sitemap", to: "home#sitemap", via: "get"
	match "/tos", to: "home#tos", via: "get"
	match "/pp", to: "home#pp", via: "get"
	match "/stat", to: "home#stat", via: "get"

	match "/signin", to: "users#signin", via: "get"
	match "/auth/:provider/callback", :to => "sessions#create", via: "get"
	match "/auth/failure", :to => "sessions#failure", via: "get"
	match "/signout", :to => "sessions#destroy", via: "get"
	match "/users/:id/email", to: "users#email", via: "get"

	resources :ingredients
	resources :ingredient_synonyms
	resources :products
	resources :users
	resources :manufacturers
	resources :brands
	resources :cities
	resources :labels
	resources :features
	resources :nutvals

	resources :inquiries
	match "/inquiries/new", to: "inquiries#create2", via: "post"
	resources :comments

	resources :j_product_features
	resources :j_product_labels
	resources :j_ingredient_classnames
	
	resources :classnames
	resources :packagematerials
	resources :categories
	resources :subcategories
	resources :veganities

end

app/controllers/home_controller.rb
# HomeController
class HomeController < ApplicationController
protect_from_forgery :except => [:search, :msearch]

  # search via http
  def search
    @search = params[:search]
    if !@search.blank?
      @product = Product.select(:id).where("gtin = ? or lower(name) like ?", @search.to_i, "%"+UnicodeUtils.downcase(@search.to_s.downcase)+"%")
      # @products = Product.search(@search)
      if @product.any?
	if @product.size == 1
	  redirect_to product_path(@product.first)
	end
      end
    end
  end

  # mobile search (AJAX/JSON)
  def msearch
    @search = params[:search].to_i
    respond_to do |format|
      if !@search.blank?
	@product = Product.where("gtin = ?", @search).first
	if !@product.blank? # and params[:callback]
	  #format.json { render action: 'search', status: :found, :callback => params[:callback] }
	  format.json { render :json => @product.to_json, :callback => params[:callback] }
	else
	  format.json { render :json => { :error => "No such product!"}, :callback => params[:callback] }
	  # status: 404, 
	end
      end
    end
  end
  
  # about
  def about
  end

  # index
  def index
  end

  # contact
  def contact
  end

  # sitemap
  def sitemap
  end
  
  # tos
  def tos
  end
  
  # pp
  def pp
  end
  
  private
    # permit something FIXME not in use?
    def p
      params.require(:product).permit(:gtin)
    end
end

app/helpers/home_helper.rb
# HomeHelper
module HomeHelper
end

app/views/home/_search.html.erb
<%= form_tag({:controller => "home", :action => "search"}, :method => "post") do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], :autofocus => "", :autocomplete => "on", :required => "required", :class => "span3", min: 3 %>
    <button type="submit" class="btn"><%= t(:search_button) %></button>
  </div>
<% end %>

app/views/home/about.html.erb
<% provide(:title, t(:about_title)) %>
	<h1><%= t :about_title %></h1>

<p>Diese Seite soll verschiedene Fragen klären.</p>

<h3><abbr title="Frequently Asked Questions">FAQ</abbr></h3>

<div class="faq">

	<h4>Was bedeutet Veganität?</h4>
	<p>Diese bedeutet wie bzw. ob etwas vegan ist.</p>
	<hr>

	<h4>Wie wird die Veganität berechnet?</h4>
	<p>Die Veganität eines Produktes wird durch diese 3 Faktoren berechnet:</p>
	<ul>
		<li>Zutaten</li>
		<li>Quelle bzw. Produktanfragen</li>
		<li>Kommentare</li>
	</ul>
	<p>Die Zutaten werden dabei jeweils auf die Veganität untersucht und ergeben somit schonmal eine Basis für die Veganität.<br>
	Dabei können natürlich immer noch tierische Bestandteile nicht deklariert werden, weil sie nicht deklarierungspflichtig sind oder im Herstellungsprozess verwendet wurden. In diesem Fall kann eine Produktanfrage gestellt werden, die dies klären soll.<br>
	Gibt es dabei oder nach einiger Zeit Fragen, können die Kommentare dazu genutzt werden, darauf hinzuweisen.</p>
	<hr>

	<h4>Sind alle Daten wirklich frei und können heruntergeladen werden?</h4>
	<p>Jein. Es sind alle bis auf persönliche Daten frei, d.h. die Tabellen <code>users</code> und <code>emailhashes</code> sind nicht frei.<br>
	Alle anderen Daten sind frei und können <a href="//dump.yava.yhaupenthal.org">hier als <a href="http://www.postgresql.org/">PostgreSQL</a>-Dump heruntergeladen werden</a>.<br>
	Drei Dateien sind dabei relevant:</p>
	<ul>
		<li><code>dump_without_schema-2013-07-10-21-42-00.pg.dump</code></li>
		<li><code>dump_with_schema-2013-07-10-21-42-00.pg.dump</code></li>
		<li><code>schema-2013-07-10-21-42-00.pg.sch</code></li>
	</ul>
	<p>Die drei Dateien werden täglich neu erstellt - was am Zeitstempel, in diesem Fall <code>2013-07-10-21-42-00</code> zu erkennen ist.<br>
	Das Schema enthält dabei alle <code>Copy</code>-Befehle, um die Datenbank zu erstellen. Eine Beispiel-Tabelle für <code>users</code> (mit Schema) <a href="//dump.yava.yhaupenthal.org/users-example.pg.dump">gibt es hier</a>, eine für <code>emailhashes</code> <a href="//dump.yava.yhaupenthal.org/emailhashes-example.pg.dump">hier</a>.<br>
	Die beiden anderen Dateien enthalten entweder alle Daten - bis auf <code>users</code> und <code>emailhashes</code> (und das Schema).</p>
	<p>In Zukunft soll es noch inkrementelle Dateien und/oder eine API geben, um die Last auf dem Server zu reduzieren.</p>
	<hr>

	<h4>Wieso kann ich mich nur über die vorgegebenen Anbieter anmelden?</h4>
	<p>Ich wollte es vermeiden, auf dem Server Passwörter zu speichern und stattdessen Dienste zu benutzen, wo viele schon einen Account haben.<br>
	In Zeiten von <a href="https://de.wikipedia.org/wiki/Prism">Prism</a> ist das natürlich nicht optimal, daher meldet mir gerne neue Anbieter (hier gibt es einige: <a href="https://openid.net/get-an-openid/">[1]</a>, <a href="https://de.wikipedia.org/wiki/OpenID#Spezialisierte_OpenID-Anbieter">[2]</a>, <a href="http://openiddirectory.com/openid-providers-c-1.html">[3]</a>, <a href="https://github.com/intridea/omniauth/wiki/List-of-Strategies">[4]</a>) bzw. <a href="http://blog.brockha.us/archives/491-Einen-eigenen-OpenID-Server-einrichten.html">baut eigene</a>.<br>
	Ich brauche generell nicht viel an Daten von einer*einem Anbieter*in.</p>
	<hr>

	<h4>Gemeinfreiheit? Warum? Und was ist das?</h4>
	<p>Gemeinfreiheit bedeutet im Prinzip, dass alle Daten frei sind und größtmögliche Transparenz vorherrscht. Die Daten gehören somit der Gemeinheit, also allen.<br>
	Ich bezeichne das als Win-Win-Situation für alle, denn die Verbraucher*innen haben mehr Informationen über die Lebensmittel und gleichzeitig wird so für die Hersteller*innen geworben.</p>
	<p>Als Lizenz habe ich mich für den Einsatz von <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.de">CC0</a> entschieden.<br>
	Dies gilt allerdings nur für die oben angegeben Daten, nicht den Code an sich. Dieser ist als <a href="https://www.gnu.org/licenses/gpl.txt">GPLv3</a> auf <a href="https://github.com/tohn/bachelor">Github</a> verfügbar.</p>
	<hr>

	<h4>Gibt es das auch als App?</h4>
	<p>Um alles schön plattformübergreifend zu halten, d.h. für alle (mobilen) Betriebssysteme nutzbar zu sein, soll es YAVA auch als App geben.<br>
	<a href="//yhaupenthal.org/bachelor.htm">Hier gibt es</a> die Android-Version.</p>
	<hr>
	
	<h4>Was sollen die Punkte?</h4>
	<p>Die Punkte sollen einen Anreiz bieten, etwas zu "leisten". 
Verschiedene Aktionen werden damit mit unterschiedlichen Punkten "vergütet".</p>
	<hr>
	
	<h4>Was wird beim Anmelden über mich gespeichert?</h4>
	<p>Ich brauche lediglich einen Namen, einen Nicknamen und eine E-Mailadresse.<br>
	Zusätzlich bekomme ich von dem*der Anbieter*in noch eine UID, die aber nur zum Anmelden genutzt wird.</p>
	<p>Der Name wird dabei nur genutzt, wenn du eine Produktanfrage sendest und kann entweder in der Produktanfrage sichtbar sein (und damit für alle), oder durch "XYZ" ersetzt werden.<br>
	Der Nickname wird überall angezeigt und identifiziert euch innerhalb der Seite.<br>
	Die E-Mailadresse wird ebenso wie der Name für Produktanfragen benutzt (als <code>From</code>)</p>
	<p>Alle drei Informationen können im Profil geändert werden.</p>
	<hr>

	<h4>Ich habe noch eine Frage!</h4>
	<p>Das ist zwar keine Frage, aber du kannst <a href="//yhaupenthal.org/contact.htm">mich gerne kontaktieren</a>.</p>
	<p>Insbesondere freue ich mich über Fehlermeldungen und Verbesserungsvorschläge!</p>


</div>

app/views/home/index.html.erb
<% provide(:title, t(:index_title)) %>

<div class="center hero-unit">
	<h1><%= t :index %></h1>

	<h4><%= t(:yava_info_html, :href => link_to(t(:yava_info_href_html), "http://yhaupenthal.org/bachelor.htm")) %></h4>

	<hr>

	<div class="row">
	<% if current_user %>
			<p><%= t :welcome %> <%= link_to current_user.nickname, user_path(current_user.id) %>!</p>
			<hr>
	<div class="span5">
		<% if Product.any? %>
			<p><%= t :complete_products %></p><p>
			<% Product.limit(5).select(:id, :name).where("integrity < 100").order(:integrity).map do |p| %>
				<%= link_to p.name, product_path(p.id) %><br>
		<% end %></p>
		<% end %>
	</div>
	<% else %>
		<p><%= link_to t(:signin), signin_path, class: "btn btn-large btn-primary" %></p>
		<hr>
	<% end %>

	<div class="span5">
		<% if Product.any? %>
			<p><%= t :newest_products %></p><p>
			<% Product.limit(5).select(:id, :name).order(:created_at).reverse_order.map do |p| %>
				<%= link_to p.name, product_path(p.id) %><br>
			<% end %></p>
		<% end %>
		<p>
		  <%= link_to t("form.new", genus: t("form.n"), model: t("products_title.one")), new_product_path, { :class => "btn" } %>
		</p>
	</div>
	</div>

</div>

app/views/home/pp.html.erb
<% provide(:title, t(:pp_title)) %>

<h1><%= t :pp_title %></h1>

TBD

app/views/home/search.html.erb
<% provide(:title, t(:search_title)) %>

<h1><%= t :search_title %></h1>

<div class="center">
<!--		<p><%#= t :search_desc %></p>-->
<p>Suche nach <abbr title="Global Trade Item Number"><a href="https://de.wikipedia.org/wiki/GTIN">GTIN</a></abbr>
<a href="#" data-toggle="tooltip" data-html="true" title="<p><%= t(:search_tooltip) %></p><p><img alt='example barcode' width='258.5px' height='208.5px' src='//yava.yhaupenthal.org/images/barcode.png'></p>" data-placement="bottom" class="ttba">[?]</a> oder Produktname
</p>


<% if @search && @product.blank? %>
  <p><%= t(:search_no_result) %><br>
  <%= t(:search_new_product_1) %> <%= link_to t(:search_new_product_2), new_product_path(:gtin => @search) %>?</p>
  <hr>
  <p><%= link_to t(:search_new), search_path %></p>
<% elsif @search && @product.any? %>
  <p><%= t(:search_many_results) %></p>
  <p><% @product.map do |p| %>
    <%= link_to Product.find_by_id(p).name, product_path(p) %><br>
  <% end %></p>
  <hr>
  <p><%= link_to t(:search_new), search_path %></p>
<% else %>
  <%= render :partial => "search" %>
<% end %>

</div>

app/views/home/sitemap.html.erb
<% provide(:title, t(:sitemap_title)) %>

<h1><%= t(:sitemap_title) %></h1>

<%# for i in * ; do echo "<%= link_to t(\"${i}_title.other\"), ${i}_path % ><br>" ; done | grep -v -e home -e layouts -e sessions -e yava_mailer %>

<p>
<%= link_to t("brands_title.other"), brands_path %><br>
<%= link_to t("categories_title.other"), categories_path %><br>
<%= link_to t("cities_title.other"), cities_path %><br>
<%= link_to t("classnames_title.other"), classnames_path %><br>
<%= link_to t("comments_title.other"), comments_path %><br>
<%= link_to t("features_title.other"), features_path %><br>
<%= link_to t("ingredients_title.other"), ingredients_path %><br>
<%= link_to t("inquiries_title.other"), inquiries_path %><br>
<%#= link_to t("j_product_comments_title.other"), j_product_comments_path %>
<%= link_to t("j_product_features_title.other"), j_product_features_path %><br>
<%#= link_to t("j_product_inquiries_title.other"), j_product_inquiries_path %>
<%= link_to t("j_product_labels_title.other"), j_product_labels_path %><br>
<%= link_to t("labels_title.other"), labels_path %><br>
<%= link_to t("manufacturers_title.other"), manufacturers_path %><br>
<%= link_to t("nutvals_title.other"), nutvals_path %><br>
<%= link_to t("packagematerials_title.other"), packagematerials_path %><br>
<%= link_to t("products_title.other"), products_path %><br>
<%= link_to t("subcategories_title.other"), subcategories_path %><br>
<%= link_to t("users_title.other"), users_path %>
</p>

<hr>

<p>
<%= link_to t("index_title"), root_path %><br>
<%= link_to t("about_title"), about_path %><br>
<%= link_to t("search_title"), search_path %><br>
<%= link_to t("sitemap_title"), sitemap_path %><br>
<%= link_to t("tos_title"), tos_path %><br>
<%= link_to t("pp_title"), pp_path %><br>
<%= link_to t("stat_title"), stat_path %>
</p>

app/views/home/stat.html.erb
<% provide(:title, t(:stat_title)) %>

<h1><%= t :stat_title %></h1>

<p><b><%= link_to t("products_title.other"), products_path %>:</b> <%= Product.count %></p>

<%= t(:stat_thereof) %>
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th><%= t("veganities_title.one") %></th>
      <th><%= t(:stat_count) %></th>
    </tr>
  </thead>
  <tbody>
  <% Veganity.all.map do |v| %>
    <tr class="<%= v.color %>">
      <td><b><%= v.name %></b></td>
      <td><%= Product.where("veganity_id = ?", v.id).count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p><b><%= link_to t("ingredients_title.other"), ingredients_path %>:</b> <%= Ingredient.where("not hide").count %></p>

<%= t(:stat_thereof) %>
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th><%= t("veganities_title.one") %></th>
      <th><%= t(:stat_count) %></th>
      <th><%= t(:stat_count) + " " + t(:stat_fixed) %></th>
    </tr>
  </thead>
  <tbody>
  <% Veganity.all.map do |v| %>
    <tr class="<%= v.color %>">
      <td><b><%= v.name %></b></td>
      <td><%= Ingredient.where("veganity_id = ? and not hide", v.id).count %></td>
      <td><%= Ingredient.where("veganity_id = ? and not hide and fixed", v.id).count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p><b><%= link_to t("users_title.other"), users_path %>:</b> <%= User.where("permission_id != ?", User::PERMISSIONS_DEACTIVATED).count %></p>

<%= t(:stat_thereof) %>
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th><%= t("providers_title.one") %></th>
      <th><%= t(:stat_count) %></th>
    </tr>
  </thead>
  <tbody>
  <% Provider.all.map do |p| %>
    <tr>
      <td><b><%= p.fullname %></b></td>
      <td><%= User.where("provider_id = ? and permission_id != ?", p.id, User::PERMISSIONS_DEACTIVATED).count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/home/tos.html.erb
<% provide(:title, t(:tos_title)) %>

<h1><%= t(:tos_title) %></h1>

Da alle Daten zur freien Nutzung zu Verfügung gestellt werden, stimmst du hiermit zu, alle Daten, die du einträgst (Produkte, Kommentare, Produktanfragen, Bilder, etc.) zur freien Verfügung zu stellen.
Die Lizenz hierfür ist <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.de">CC0</a>.
Ausgeschlossen von diesen Daten sind deine persönlichen Daten wie Name und E-Mailadresse.

<!--

https://en.wikipedia.org/wiki/Terms_of_service

<h3>Disambiguation/definition of key words and phrases</h3>

<h3>User rights and responsibilities</h3>

<h4>Proper or expected usage; potential misuse</h4>

Accountability for online actions, behavior, and conduct
Privacy policy outlining the use of personal data
Payment details such as membership or subscription fees, etc.
Opt-out policy describing procedure for account termination, if available
<h4>Privacy Policy</h4>

https://de.wikipedia.org/wiki/Privacy_policy

<h4>Opt-Out</h3>

<h3>Disclaimer/Limitation of Liability clarifying the site's legal liability for damages incurred by users</h3>
<h3>User notification upon modification of terms, if offered</h3>


<h4>Copyright der Daten</h4>
-->