config/routes.rb
Yava::Application.routes.draw do

	root 'home#index'
	
	match "/search", to: "home#search", via: "get"
	match "/search", to: "home#search", via: "post"
	match "/msearch", to: "home#msearch", via: "get"
	match "/msearch", to: "home#msearch", via: "post"
	match "/about", to: "home#about", via: "get"
	match "/index", to: "home#index", via: "get"
	match "/sitemap", to: "home#sitemap", via: "get"
	match "/tos", to: "home#tos", via: "get"
	match "/pp", to: "home#pp", via: "get"
	match "/stat", to: "home#stat", via: "get"

	match "/signin", to: "users#signin", via: "get"
	match "/auth/:provider/callback", :to => "sessions#create", via: "get"
	match "/auth/failure", :to => "sessions#failure", via: "get"
	match "/signout", :to => "sessions#destroy", via: "get"
	match "/users/:id/email", to: "users#email", via: "get"

	resources :ingredients
	resources :ingredient_synonyms
	resources :products
	resources :users
	resources :manufacturers
	resources :brands
	resources :cities
	resources :labels
	resources :features
	resources :nutvals

	resources :inquiries
	match "/inquiries/new", to: "inquiries#create2", via: "post"
	resources :comments

	resources :j_product_features
	resources :j_product_labels
	resources :j_ingredient_classnames
	
	resources :classnames
	resources :packagematerials
	resources :categories
	resources :subcategories
	resources :veganities

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	validates :name, presence: true, uniqueness: {case_sensitive: false}

#	has_one :category_id, as: "Category"
#	belongs_to :category #, as: "Category"
#	belongs_to :category
#	belongs_to :product
	has_many :subcategory
end

app/controllers/categories_controller.rb
# CategoriesController
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(:page => params[:page])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

app/helpers/categories_helper.rb
# CategoriesHelper
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if current_user %>
	<%= simple_form_for(@category, :html => { :class => 'form-horizontal' }) do |f| %>
	<%= render "layouts/submit_error", :errors => @category.errors %>

	<div class="form-inputs">
		<%= f.input :name %>
	</div>

	<div class="form-actions">
		<%= f.button :submit, :class => 'btn-primary' %>
		<%= submit_tag t(:form_cancel), :type => :reset, :class => "btn btn-danger" %>
	</div>
<% end %>
<% else %>
	<%= no_rights %>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t("form.edit", model: t("categories_title.one")) %></h1>

<%= render 'form' %>

<hr>

<p>
	<%= link_to t(:link_show, model: t("categories_title.one")), @category %> |
	<%= link_to t(:link_back, model: t("categories_title.other")), categories_path %>
</p>

app/views/categories/index.html.erb
<h1><%= t("categories_title.other") %></h1>

<div class="center">
	<%= will_paginate @categories %>
</div>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
						<th><%= t("activerecord.attributes.category.name") %></th>
					</tr>
	</thead>

	<tbody>
		<%# @categories.order("coalesce(category_id, id), category_id is not null, id").each do |category| %>
		<% @categories.order("lower(name) asc").each do |category| %>
		<tr>
						<td><%= link_to category.name, category_path(category.id) %></td>
					</tr>
		<% end %>
	</tbody>
</table>

<div class="center">
	<%= will_paginate @categories %>
</div>

<hr>

<p>
	<%= link_to t("form.new", genus: t("form.f"), model: t("categories_title.one")), new_category_path %>
</p>

app/views/categories/new.html.erb
<h1><%= t("form.new", genus: t("form.f"), model: t("categories_title.one")) %></h1>

<%= render 'form' %>

<hr>

<p>
	<%= link_to t(:link_back, model: t("categories_title.other")), categories_path %>
</p>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p><b><%= t("activerecord.attributes.category.subcategory") %>:</b></p>

<% @category.subcategory.map do |s| %>
		<%= link_to s.name, subcategory_path(s.id) %>
<% end %>

<hr>

<p>
	<%= link_to t(:link_edit, model: t("categories_title.one")), edit_category_path(@category) %> |
	<%= link_to t(:link_back, model: t("categories_title.other")), categories_path %>
</p>